### ISSUE TITLE
Mmg 5.7.3 CMake configuration is broken

### ISSUE THREAD

**Issue by jcortial-safran** [conda-forge/mmgsuite-feedstock#9]
The CMake configuration is broken in mmg 5.7.3 since it looks for VTK even when mmg was not compiled with mmg support.

There is a fix in the main branch (https://github.com/MmgTools/mmg/pull/267) but it has been included in a new release yet.

Would it me possible to release mmg 5.7.2 in the meantime ?

**Comment by ldallolio** [comment]
Hi, I think there is still some work to be done for the 5.7.2 (tests in some environments not passing yet) :

https://github.com/conda-forge/mmgsuite-feedstock/pull/6

**Comment by jcortial-safran** [comment]
5.8.0 has just been released, issue is obsolete : https://github.com/MmgTools/mmg/releases/tag/v5.8.0
